### ISSUE TITLE
rpm broken by default (temp files/folders get removed after a while)

### ISSUE THREAD

**Issue by jalbstmeijer** [bboozzoo/snapd-amazon-linux#10]
Hi @bboozzoo ,

I'm tracking an issue I have after a while with snap installed lxc/lxd on Amazon Linux 2

```
[root@serverx ~]# lxc stop xxx-1 
Error: open /tmp/lxd_config_1335223730: no such file or directory
```
It seems systemd is cleaning /tmp and removing /tmp/snap.lxd/tmp, causing the issue above.

This is prevented by other rpm package releases by placing a /usr/lib/tmpfiles.d/snapd.conf like  https://github.com/snapcore/snapd/blob/master/data/systemd-tmpfiles/snapd.conf

Should the spec be re-synced with upstream?

Kind regards, Justin

**Comment by bboozzoo** [comment]
I believe this should be fixed already.
