### ISSUE TITLE
Trying to install on amazon linux 2023 but getting an error..

### ISSUE THREAD

**Issue by Dweller** [bboozzoo/snapd-amazon-linux#26]
# yum install snapd
Last metadata expiration check: 0:03:28 ago on Thu Sep  5 12:44:21 2024.
Error:
 Problem: package snapd-2.63-1.amzn2023.1.x86_64 requires snapd-selinux = 2.63-1.amzn2023.1, but none of the providers can be installed
  - conflicting requests
  - nothing provides selinux-policy >= 37.22-1.amzn2023.0.2 needed by snapd-selinux-2.63-1.amzn2023.1.noarch
  - nothing provides selinux-policy-base >= 37.22-1.amzn2023.0.2 needed by snapd-selinux-2.63-1.amzn2023.1.noarch
(try to add '--skip-broken' to skip uninstallable packages)

**Comment by Dweller** [comment]
Turns out that the snapd in this repo does work as long as its a EC2 Amazon 2023 and this issue only occurs with the Amazon 2023 cloud image that is usable under VMWare..

**Comment by bboozzoo** [comment]
The repo is built against the latest available version of 2023 release. See https://docs.aws.amazon.com/linux/al2023/ug/managing-repos-os-updates.html for details on how the release versions work. While most of the time the package should work on older versions, the SELinux module is built with a very specific policy version so this effectively limits the number of compatible release versions.

Note, you can always grab the src.rpm and rebuild the packages yourself to match your system.
